name: wise_wallet
description: "An app for personal finances."

publish_to: 'none' 
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  objectbox: ^2.4.0
  build_runner: ^2.4.8
  path_provider: ^2.1.2
  path: ^1.9.0
  objectbox_generator: ^2.5.0
  objectbox_flutter_libs: ^2.5.0
  fl_chart: ^1.1.1
  google_fonts: ^6.3.2
  dartz: ^0.10.1
  flutter_animate: ^4.5.2
  get_storage: ^2.1.1
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  open_filex: ^4.7.0
  local_auth: ^3.0.0
  quick_actions: ^1.1.0
  home_widget: ^0.9.0
  firebase_core: ^3.11.0
  firebase_analytics: ^11.4.1
  firebase_crashlytics: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: 'app/data/datasource/objectbox'
  # Or optionally specify the lib and test output folder separately.
  # output_dir:
  #   lib: custom
  #   test: other
