// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../../../app/data/models/bank_discount_dao.dart';
import '../../../../app/data/models/category_dao.dart';
import '../../../../app/data/models/credit_card_dao.dart';
import '../../../../app/data/models/expense_dao.dart';
import '../../../../app/data/models/income_dao.dart';
import '../../../../app/data/models/subscription_dao.dart';
import '../../../../app/data/models/tag_dao.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5919817927012936905),
    name: 'ExpenseDao',
    lastPropertyId: const obx_int.IdUid(10, 5620443540309895286),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8467154191867697575),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 980807865786412414),
        name: 'value',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2192930994010682160),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5272017983793239894),
        name: 'time',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2796075415949339620),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 4613352209867354644),
        relationField: 'category',
        relationTarget: 'CategoryDao',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5620443540309895286),
        name: 'cardId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 2834181971530382959),
        relationField: 'card',
        relationTarget: 'CreditCardDao',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(4, 24130832137686415),
        name: 'tags',
        targetId: const obx_int.IdUid(4, 3601738121799794424),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3601738121799794424),
    name: 'TagDao',
    lastPropertyId: const obx_int.IdUid(4, 6424160278689821139),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5518069033967568717),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7866011984642990259),
        name: 'tag',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6383428610470993746),
        name: 'color',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6424160278689821139),
        name: 'displayOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 3393782162671296317),
    name: 'CategoryDao',
    lastPropertyId: const obx_int.IdUid(8, 494872354336738956),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6366750666482516730),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1476329779750957291),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8721166927382276505),
        name: 'iconCodePoint',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2545399002649085515),
        name: 'group',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7755097635590964978),
        name: 'color',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7824590487083745201),
        name: 'parentId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 494872354336738956),
        name: 'displayOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 8445603323851752585),
    name: 'CreditCardDao',
    lastPropertyId: const obx_int.IdUid(9, 6438333928535064894),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4961737592928691345),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8558151195287283451),
        name: 'cardNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5335799391301192086),
        name: 'holderName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3268434557798066084),
        name: 'expiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7357709932517450156),
        name: 'closingDay',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2804694125692121516),
        name: 'dueDay',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3385977480107580113),
        name: 'color',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5824745874490540154),
        name: 'cardType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6438333928535064894),
        name: 'bankName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 4682781076433017614),
    name: 'SubscriptionDao',
    lastPropertyId: const obx_int.IdUid(10, 3861221567018217888),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4548396326727660402),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4084577404653065970),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4438940236899984087),
        name: 'value',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8806360343990798655),
        name: 'cycle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7863802301125278495),
        name: 'nextPaymentDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 660564981356285830),
        name: 'isAutoPay',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8663098719702650251),
        name: 'taxPercentage',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7273677235937782734),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8182732957857453030),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 3298386781401118933),
        relationField: 'category',
        relationTarget: 'CategoryDao',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3861221567018217888),
        name: 'cardId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 1803719598457424279),
        relationField: 'card',
        relationTarget: 'CreditCardDao',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(5, 8560510091104629211),
        name: 'tags',
        targetId: const obx_int.IdUid(4, 3601738121799794424),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 3354584546240971987),
    name: 'BankDiscountDao',
    lastPropertyId: const obx_int.IdUid(13, 6162972385868373437),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8674725321655793364),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3984877170839995375),
        name: 'bankName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3263647413679923250),
        name: 'discountPercentage',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5855358590782649770),
        name: 'daysOfWeekCsv',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 57883172598926493),
        name: 'paymentMethod',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5323689072793739046),
        name: 'expiryDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4717929861857819099),
        name: 'maxCashback',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4335132045868899882),
        name: 'installments',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6599042422452136374),
        name: 'bankColor',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7197132442869337009),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4665753890794428711),
        name: 'merchantName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2170867165309409881),
        name: 'specificDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6162972385868373437),
        name: 'note',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 3912907808824102914),
    name: 'IncomeDao',
    lastPropertyId: const obx_int.IdUid(5, 8782898853105616480),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3451198809886046964),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 215161903591326553),
        name: 'value',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1861395626675204789),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3137571142956319484),
        name: 'time',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8782898853105616480),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 472417504103244167),
        relationField: 'category',
        relationTarget: 'CategoryDao',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 3912907808824102914),
    lastIndexId: const obx_int.IdUid(6, 472417504103244167),
    lastRelationId: const obx_int.IdUid(5, 8560510091104629211),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      3124102123521736051,
      507036025836838464,
      3158100299059240116,
    ],
    retiredIndexUids: const [1128386827182227114],
    retiredPropertyUids: const [
      3879372550089706277,
      8381641229841950575,
      72597092580267512,
      849968182285221238,
      640440764480911258,
      2238330895478964221,
      3265471650160425111,
      1494924912565155595,
      2265806399890665750,
      2922509187325330259,
    ],
    retiredRelationUids: const [3099708585342056500],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ExpenseDao: obx_int.EntityDefinition<ExpenseDao>(
      model: _entities[0],
      toOneRelations: (ExpenseDao object) => [object.category, object.card],
      toManyRelations: (ExpenseDao object) => {
        obx_int.RelInfo<ExpenseDao>.toMany(4, object.id): object.tags,
      },
      getId: (ExpenseDao object) => object.id,
      setId: (ExpenseDao object, int id) {
        object.id = id;
      },
      objectToFB: (ExpenseDao object, fb.Builder fbb) {
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.value);
        fbb.addOffset(2, noteOffset);
        fbb.addInt64(3, object.time.millisecondsSinceEpoch);
        fbb.addInt64(7, object.category.targetId);
        fbb.addInt64(9, object.card.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final valueParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final timeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = ExpenseDao(
          value: valueParam,
          note: noteParam,
          time: timeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.category.attach(store);
        object.card.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.card.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<ExpenseDao>(
          object.tags,
          store,
          obx_int.RelInfo<ExpenseDao>.toMany(4, object.id),
        );
        return object;
      },
    ),
    TagDao: obx_int.EntityDefinition<TagDao>(
      model: _entities[1],
      toOneRelations: (TagDao object) => [],
      toManyRelations: (TagDao object) => {},
      getId: (TagDao object) => object.id,
      setId: (TagDao object, int id) {
        object.id = id;
      },
      objectToFB: (TagDao object, fb.Builder fbb) {
        final tagOffset = fbb.writeString(object.tag);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, tagOffset);
        fbb.addInt64(2, object.color);
        fbb.addInt64(3, object.displayOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final tagParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final colorParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final displayOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = TagDao(
          tag: tagParam,
          color: colorParam,
          displayOrder: displayOrderParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    CategoryDao: obx_int.EntityDefinition<CategoryDao>(
      model: _entities[2],
      toOneRelations: (CategoryDao object) => [],
      toManyRelations: (CategoryDao object) => {},
      getId: (CategoryDao object) => object.id,
      setId: (CategoryDao object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryDao object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final groupOffset = object.group == null
            ? null
            : fbb.writeString(object.group!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.iconCodePoint);
        fbb.addOffset(3, groupOffset);
        fbb.addInt64(5, object.color);
        fbb.addInt64(6, object.parentId);
        fbb.addInt64(7, object.displayOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final iconCodePointParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final groupParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final colorParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final parentIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final displayOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = CategoryDao(
          name: nameParam,
          iconCodePoint: iconCodePointParam,
          group: groupParam,
          color: colorParam,
          parentId: parentIdParam,
          displayOrder: displayOrderParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    CreditCardDao: obx_int.EntityDefinition<CreditCardDao>(
      model: _entities[3],
      toOneRelations: (CreditCardDao object) => [],
      toManyRelations: (CreditCardDao object) => {},
      getId: (CreditCardDao object) => object.id,
      setId: (CreditCardDao object, int id) {
        object.id = id;
      },
      objectToFB: (CreditCardDao object, fb.Builder fbb) {
        final cardNumberOffset = fbb.writeString(object.cardNumber);
        final holderNameOffset = fbb.writeString(object.holderName);
        final expiryDateOffset = fbb.writeString(object.expiryDate);
        final bankNameOffset = object.bankName == null
            ? null
            : fbb.writeString(object.bankName!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cardNumberOffset);
        fbb.addOffset(2, holderNameOffset);
        fbb.addOffset(3, expiryDateOffset);
        fbb.addInt64(4, object.closingDay);
        fbb.addInt64(5, object.dueDay);
        fbb.addInt64(6, object.color);
        fbb.addInt64(7, object.cardType);
        fbb.addOffset(8, bankNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final cardNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final holderNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final expiryDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final closingDayParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final dueDayParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final colorParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final cardTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final bankNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = CreditCardDao(
          id: idParam,
          cardNumber: cardNumberParam,
          holderName: holderNameParam,
          expiryDate: expiryDateParam,
          closingDay: closingDayParam,
          dueDay: dueDayParam,
          color: colorParam,
          cardType: cardTypeParam,
          bankName: bankNameParam,
        );

        return object;
      },
    ),
    SubscriptionDao: obx_int.EntityDefinition<SubscriptionDao>(
      model: _entities[4],
      toOneRelations: (SubscriptionDao object) => [
        object.category,
        object.card,
      ],
      toManyRelations: (SubscriptionDao object) => {
        obx_int.RelInfo<SubscriptionDao>.toMany(5, object.id): object.tags,
      },
      getId: (SubscriptionDao object) => object.id,
      setId: (SubscriptionDao object, int id) {
        object.id = id;
      },
      objectToFB: (SubscriptionDao object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final cycleOffset = fbb.writeString(object.cycle);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.value);
        fbb.addOffset(3, cycleOffset);
        fbb.addInt64(4, object.nextPaymentDate.millisecondsSinceEpoch);
        fbb.addBool(5, object.isAutoPay);
        fbb.addFloat64(6, object.taxPercentage);
        fbb.addOffset(7, noteOffset);
        fbb.addInt64(8, object.category.targetId);
        fbb.addInt64(9, object.card.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final cycleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final nextPaymentDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isAutoPayParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final taxPercentageParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final object = SubscriptionDao(
          id: idParam,
          name: nameParam,
          value: valueParam,
          cycle: cycleParam,
          nextPaymentDate: nextPaymentDateParam,
          isAutoPay: isAutoPayParam,
          taxPercentage: taxPercentageParam,
          note: noteParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.category.attach(store);
        object.card.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.card.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<SubscriptionDao>(
          object.tags,
          store,
          obx_int.RelInfo<SubscriptionDao>.toMany(5, object.id),
        );
        return object;
      },
    ),
    BankDiscountDao: obx_int.EntityDefinition<BankDiscountDao>(
      model: _entities[5],
      toOneRelations: (BankDiscountDao object) => [],
      toManyRelations: (BankDiscountDao object) => {},
      getId: (BankDiscountDao object) => object.id,
      setId: (BankDiscountDao object, int id) {
        object.id = id;
      },
      objectToFB: (BankDiscountDao object, fb.Builder fbb) {
        final bankNameOffset = fbb.writeString(object.bankName);
        final daysOfWeekCsvOffset = fbb.writeString(object.daysOfWeekCsv);
        final paymentMethodOffset = fbb.writeString(object.paymentMethod);
        final installmentsOffset = object.installments == null
            ? null
            : fbb.writeString(object.installments!);
        final categoryOffset = object.category == null
            ? null
            : fbb.writeString(object.category!);
        final merchantNameOffset = object.merchantName == null
            ? null
            : fbb.writeString(object.merchantName!);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, bankNameOffset);
        fbb.addFloat64(2, object.discountPercentage);
        fbb.addOffset(3, daysOfWeekCsvOffset);
        fbb.addOffset(4, paymentMethodOffset);
        fbb.addInt64(5, object.expiryDate?.millisecondsSinceEpoch);
        fbb.addFloat64(6, object.maxCashback);
        fbb.addOffset(7, installmentsOffset);
        fbb.addInt64(8, object.bankColor);
        fbb.addOffset(9, categoryOffset);
        fbb.addOffset(10, merchantNameOffset);
        fbb.addInt64(11, object.specificDate?.millisecondsSinceEpoch);
        fbb.addOffset(12, noteOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final expiryDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final specificDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final bankNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final discountPercentageParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final daysOfWeekCsvParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final paymentMethodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final expiryDateParam = expiryDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(expiryDateValue);
        final maxCashbackParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final installmentsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final bankColorParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final merchantNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final specificDateParam = specificDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(specificDateValue);
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final object = BankDiscountDao(
          id: idParam,
          bankName: bankNameParam,
          discountPercentage: discountPercentageParam,
          daysOfWeekCsv: daysOfWeekCsvParam,
          paymentMethod: paymentMethodParam,
          expiryDate: expiryDateParam,
          maxCashback: maxCashbackParam,
          installments: installmentsParam,
          bankColor: bankColorParam,
          category: categoryParam,
          merchantName: merchantNameParam,
          specificDate: specificDateParam,
          note: noteParam,
        );

        return object;
      },
    ),
    IncomeDao: obx_int.EntityDefinition<IncomeDao>(
      model: _entities[6],
      toOneRelations: (IncomeDao object) => [object.category],
      toManyRelations: (IncomeDao object) => {},
      getId: (IncomeDao object) => object.id,
      setId: (IncomeDao object, int id) {
        object.id = id;
      },
      objectToFB: (IncomeDao object, fb.Builder fbb) {
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.value);
        fbb.addOffset(2, noteOffset);
        fbb.addInt64(3, object.time.millisecondsSinceEpoch);
        fbb.addInt64(4, object.category.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final valueParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final timeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = IncomeDao(
          value: valueParam,
          note: noteParam,
          time: timeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ExpenseDao] entity fields to define ObjectBox queries.
class ExpenseDao_ {
  /// See [ExpenseDao.id].
  static final id = obx.QueryIntegerProperty<ExpenseDao>(
    _entities[0].properties[0],
  );

  /// See [ExpenseDao.value].
  static final value = obx.QueryDoubleProperty<ExpenseDao>(
    _entities[0].properties[1],
  );

  /// See [ExpenseDao.note].
  static final note = obx.QueryStringProperty<ExpenseDao>(
    _entities[0].properties[2],
  );

  /// See [ExpenseDao.time].
  static final time = obx.QueryDateProperty<ExpenseDao>(
    _entities[0].properties[3],
  );

  /// See [ExpenseDao.category].
  static final category = obx.QueryRelationToOne<ExpenseDao, CategoryDao>(
    _entities[0].properties[4],
  );

  /// See [ExpenseDao.card].
  static final card = obx.QueryRelationToOne<ExpenseDao, CreditCardDao>(
    _entities[0].properties[5],
  );

  /// see [ExpenseDao.tags]
  static final tags = obx.QueryRelationToMany<ExpenseDao, TagDao>(
    _entities[0].relations[0],
  );
}

/// [TagDao] entity fields to define ObjectBox queries.
class TagDao_ {
  /// See [TagDao.id].
  static final id = obx.QueryIntegerProperty<TagDao>(
    _entities[1].properties[0],
  );

  /// See [TagDao.tag].
  static final tag = obx.QueryStringProperty<TagDao>(
    _entities[1].properties[1],
  );

  /// See [TagDao.color].
  static final color = obx.QueryIntegerProperty<TagDao>(
    _entities[1].properties[2],
  );

  /// See [TagDao.displayOrder].
  static final displayOrder = obx.QueryIntegerProperty<TagDao>(
    _entities[1].properties[3],
  );
}

/// [CategoryDao] entity fields to define ObjectBox queries.
class CategoryDao_ {
  /// See [CategoryDao.id].
  static final id = obx.QueryIntegerProperty<CategoryDao>(
    _entities[2].properties[0],
  );

  /// See [CategoryDao.name].
  static final name = obx.QueryStringProperty<CategoryDao>(
    _entities[2].properties[1],
  );

  /// See [CategoryDao.iconCodePoint].
  static final iconCodePoint = obx.QueryIntegerProperty<CategoryDao>(
    _entities[2].properties[2],
  );

  /// See [CategoryDao.group].
  static final group = obx.QueryStringProperty<CategoryDao>(
    _entities[2].properties[3],
  );

  /// See [CategoryDao.color].
  static final color = obx.QueryIntegerProperty<CategoryDao>(
    _entities[2].properties[4],
  );

  /// See [CategoryDao.parentId].
  static final parentId = obx.QueryIntegerProperty<CategoryDao>(
    _entities[2].properties[5],
  );

  /// See [CategoryDao.displayOrder].
  static final displayOrder = obx.QueryIntegerProperty<CategoryDao>(
    _entities[2].properties[6],
  );
}

/// [CreditCardDao] entity fields to define ObjectBox queries.
class CreditCardDao_ {
  /// See [CreditCardDao.id].
  static final id = obx.QueryIntegerProperty<CreditCardDao>(
    _entities[3].properties[0],
  );

  /// See [CreditCardDao.cardNumber].
  static final cardNumber = obx.QueryStringProperty<CreditCardDao>(
    _entities[3].properties[1],
  );

  /// See [CreditCardDao.holderName].
  static final holderName = obx.QueryStringProperty<CreditCardDao>(
    _entities[3].properties[2],
  );

  /// See [CreditCardDao.expiryDate].
  static final expiryDate = obx.QueryStringProperty<CreditCardDao>(
    _entities[3].properties[3],
  );

  /// See [CreditCardDao.closingDay].
  static final closingDay = obx.QueryIntegerProperty<CreditCardDao>(
    _entities[3].properties[4],
  );

  /// See [CreditCardDao.dueDay].
  static final dueDay = obx.QueryIntegerProperty<CreditCardDao>(
    _entities[3].properties[5],
  );

  /// See [CreditCardDao.color].
  static final color = obx.QueryIntegerProperty<CreditCardDao>(
    _entities[3].properties[6],
  );

  /// See [CreditCardDao.cardType].
  static final cardType = obx.QueryIntegerProperty<CreditCardDao>(
    _entities[3].properties[7],
  );

  /// See [CreditCardDao.bankName].
  static final bankName = obx.QueryStringProperty<CreditCardDao>(
    _entities[3].properties[8],
  );
}

/// [SubscriptionDao] entity fields to define ObjectBox queries.
class SubscriptionDao_ {
  /// See [SubscriptionDao.id].
  static final id = obx.QueryIntegerProperty<SubscriptionDao>(
    _entities[4].properties[0],
  );

  /// See [SubscriptionDao.name].
  static final name = obx.QueryStringProperty<SubscriptionDao>(
    _entities[4].properties[1],
  );

  /// See [SubscriptionDao.value].
  static final value = obx.QueryDoubleProperty<SubscriptionDao>(
    _entities[4].properties[2],
  );

  /// See [SubscriptionDao.cycle].
  static final cycle = obx.QueryStringProperty<SubscriptionDao>(
    _entities[4].properties[3],
  );

  /// See [SubscriptionDao.nextPaymentDate].
  static final nextPaymentDate = obx.QueryDateProperty<SubscriptionDao>(
    _entities[4].properties[4],
  );

  /// See [SubscriptionDao.isAutoPay].
  static final isAutoPay = obx.QueryBooleanProperty<SubscriptionDao>(
    _entities[4].properties[5],
  );

  /// See [SubscriptionDao.taxPercentage].
  static final taxPercentage = obx.QueryDoubleProperty<SubscriptionDao>(
    _entities[4].properties[6],
  );

  /// See [SubscriptionDao.note].
  static final note = obx.QueryStringProperty<SubscriptionDao>(
    _entities[4].properties[7],
  );

  /// See [SubscriptionDao.category].
  static final category = obx.QueryRelationToOne<SubscriptionDao, CategoryDao>(
    _entities[4].properties[8],
  );

  /// See [SubscriptionDao.card].
  static final card = obx.QueryRelationToOne<SubscriptionDao, CreditCardDao>(
    _entities[4].properties[9],
  );

  /// see [SubscriptionDao.tags]
  static final tags = obx.QueryRelationToMany<SubscriptionDao, TagDao>(
    _entities[4].relations[0],
  );
}

/// [BankDiscountDao] entity fields to define ObjectBox queries.
class BankDiscountDao_ {
  /// See [BankDiscountDao.id].
  static final id = obx.QueryIntegerProperty<BankDiscountDao>(
    _entities[5].properties[0],
  );

  /// See [BankDiscountDao.bankName].
  static final bankName = obx.QueryStringProperty<BankDiscountDao>(
    _entities[5].properties[1],
  );

  /// See [BankDiscountDao.discountPercentage].
  static final discountPercentage = obx.QueryDoubleProperty<BankDiscountDao>(
    _entities[5].properties[2],
  );

  /// See [BankDiscountDao.daysOfWeekCsv].
  static final daysOfWeekCsv = obx.QueryStringProperty<BankDiscountDao>(
    _entities[5].properties[3],
  );

  /// See [BankDiscountDao.paymentMethod].
  static final paymentMethod = obx.QueryStringProperty<BankDiscountDao>(
    _entities[5].properties[4],
  );

  /// See [BankDiscountDao.expiryDate].
  static final expiryDate = obx.QueryDateProperty<BankDiscountDao>(
    _entities[5].properties[5],
  );

  /// See [BankDiscountDao.maxCashback].
  static final maxCashback = obx.QueryDoubleProperty<BankDiscountDao>(
    _entities[5].properties[6],
  );

  /// See [BankDiscountDao.installments].
  static final installments = obx.QueryStringProperty<BankDiscountDao>(
    _entities[5].properties[7],
  );

  /// See [BankDiscountDao.bankColor].
  static final bankColor = obx.QueryIntegerProperty<BankDiscountDao>(
    _entities[5].properties[8],
  );

  /// See [BankDiscountDao.category].
  static final category = obx.QueryStringProperty<BankDiscountDao>(
    _entities[5].properties[9],
  );

  /// See [BankDiscountDao.merchantName].
  static final merchantName = obx.QueryStringProperty<BankDiscountDao>(
    _entities[5].properties[10],
  );

  /// See [BankDiscountDao.specificDate].
  static final specificDate = obx.QueryDateProperty<BankDiscountDao>(
    _entities[5].properties[11],
  );

  /// See [BankDiscountDao.note].
  static final note = obx.QueryStringProperty<BankDiscountDao>(
    _entities[5].properties[12],
  );
}

/// [IncomeDao] entity fields to define ObjectBox queries.
class IncomeDao_ {
  /// See [IncomeDao.id].
  static final id = obx.QueryIntegerProperty<IncomeDao>(
    _entities[6].properties[0],
  );

  /// See [IncomeDao.value].
  static final value = obx.QueryDoubleProperty<IncomeDao>(
    _entities[6].properties[1],
  );

  /// See [IncomeDao.note].
  static final note = obx.QueryStringProperty<IncomeDao>(
    _entities[6].properties[2],
  );

  /// See [IncomeDao.time].
  static final time = obx.QueryDateProperty<IncomeDao>(
    _entities[6].properties[3],
  );

  /// See [IncomeDao.category].
  static final category = obx.QueryRelationToOne<IncomeDao, CategoryDao>(
    _entities[6].properties[4],
  );
}
